### ISSUE TITLE
Resistor Question

### ISSUE THREAD

**Issue by oXL0C0Xo** [scrapcomputing/MHzDisplayBlaster#1]
I noticed that the resistor is not listed in the BOM. I can asee that it is a 39 Ohm resistor. Do you think that I could use a 1/8 w resistor, or should this be 1/4 w? I have a bunch of 1/8 w, but if it need to be 1/4 w I will have to order those. Thanks for all of your interesting projects!

**Comment by scrapcomputing** [comment]
Thank you for reaching out. Yes, it was missing, I just added it in. 
Well, the original display had a 1/4 watt 39 Ohm resistor. The green LEDs operate at ~2V so the resistor needs to drop 3V. So its power consumption is V^2/R which is 9/39 = 0.23 watts . So yes the right value is 1/4 Watt.

However, a 39 Ohm resistor is quite low and the display looks *very* bright, and this can't be good for them in the long term. I would much rather use a 100 Ohm resistor instead, which btw looks plenty bright. For a 100 Ohm resistor 1/8 W is plenty.
