### ISSUE TITLE
2 pin turbo switch?

### ISSUE THREAD

**Issue by oXL0C0Xo** [scrapcomputing/MHzDisplayBlaster#2]
Hey there! I'm curious if there is a hack or something that I could do to get this to work with a 2 pin turbo switch, instead of having to replace the turbo switch in my case with a 3-pin? Or is the only way that this will work is if I have a 3-pin turbo switch?

**Comment by scrapcomputing** [comment]
If you use a 2-pin switch then the best option would be to get the display to print a frequency value when Turbo is ON and nothing when turbo is OFF. 
Alternatively you could use some electronics to implement a 3-pin switch, but replacing the switch would probably be a lot easier.
